### ISSUE TITLE
 PnP Bridge command data will receive the request data but has mojibake

### ISSUE THREAD

**Issue by ajbarb** [Azure/AzurePnPBridgePreview#19]
[Robert Chung] Just tried the Telemetry, Property, and Command function, and there is no problem but Command. When I send the command payload to the Arduino device, the PnP Bridge will receive the request data but has mojibake, like: “\”15\”yyyy~!y”. Here is my request command:
az iot pnp invoke-command --command-name "calibrate" --command-payload "\"15\"" --interface "http://robert.com/bridgeInterface/1.0.0" --hub-name "RobertTestHub" --device-id "TestDevice"

**Comment by usivagna** [comment]
Closing this issue as it appears to be on an old version of the bridge.
