### ISSUE TITLE
Should this be public?

### ISSUE THREAD

**Issue by legitmaxwu** [Azure/AzurePnPBridgePreview#23]
The front page README says:

"Access to this pre-release software is confidential and should not be disclosed or shared with other parties per your NDA with Microsoft."

Does that mean that this repo should not be public? Or, has there been a change to this?

Thanks,
Max

**Comment by meiwill** [comment]
This repo is in public preview.  We will update the README shortly.

**Comment by usivagna** [comment]
README has been updated
