### ISSUE TITLE
git clone sub module update failing

### ISSUE THREAD

**Issue by humblejay** [Azure/AzurePnPBridgePreview#26]
Post cloning repo, submodule update under pnpbridge fails with "Filename too long" , "index-pack failed" and other errors. 
Log attached.
[gitclonefail.log](https://github.com/Azure/AzurePnPBridgePreview/files/3575976/gitclonefail.log)

**Comment by usivagna** [comment]
This is a known issue with Windows file paths and git see:  [https://github.com/msysgit/git/pull/110](url) . You can try the following cmd to resolve the issue: `git config --system core.longpaths true`

**Comment by usivagna** [comment]
Closing this issue, as it should be addressed with the above comment. Please let me know if we need to re-visit this @humblejay .
