### ISSUE TITLE
Add headers to messages: contentType: application/json and contentEncoding:utf-8 (or utf-16, utf-32)

### ISSUE THREAD

**Issue by viv-liu** [Azure/AzurePnPBridgePreview#29]
These headers are important for messages to have because when you use IoT Central's data export feature (as well as IoT Hub routing), the data will look like a binary blob without these headers. 

See bullet 2 under "Telemetry" in [docs](https://docs.microsoft.com/en-us/azure/iot-central/core/howto-export-data-pnp?toc=/azure/iot-central-pnp/toc.json&bc=/azure/iot-central-pnp/breadcrumb/toc.json#data-format)

**Comment by viv-liu** [comment]
@usivagna from our conversation

**Comment by usivagna** [comment]
Closing the issue, as it has been raised with the relevant SDK team (see Shyamal's reference).
